name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run tests
        run: npx playwright test --ignore-snapshots
        env:
          env:
          STANDARD_USERNAME: ${{ secrets.STANDARD_USERNAME }}
          STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}
          LOCKED_OUT_USERNAME: ${{ secrets.LOCKED_OUT_USERNAME }}
          LOCKED_OUT_PASSWORD: ${{ secrets.LOCKED_OUT_PASSWORD }}
          PROBLEM_USERNAME: ${{ secrets.PROBLEM_USERNAME }}
          PROBLEM_PASSWORD: ${{ secrets.PROBLEM_PASSWORD }}
          PERFORMANCE_GLITCH_USERNAME: ${{ secrets.PERFORMANCE_GLITCH_USERNAME }}
          PERFORMANCE_GLITCH_PASSWORD: ${{ secrets.PERFORMANCE_GLITCH_PASSWORD }}
          ERROR_USERNAME: ${{ secrets.ERROR_USERNAME }}
          ERROR_PASSWORD: ${{ secrets.ERROR_PASSWORD }}
          VISUAL_USERNAME: ${{ secrets.VISUAL_USERNAME }}
          VISUAL_PASSWORD: ${{ secrets.VISUAL_PASSWORD }}